name: image-processing-delivery-rust
description: A minimal Google Cloud TypeScript Pulumi program
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-typescript
